#!/bin/bash
set -e

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=${DRONE_TAG:-$(git tag -l --contains HEAD | head -n 1)}

if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
    VERSION=$GIT_TAG
else
    VERSION="${COMMIT}${DIRTY}"
fi

TAG=${TAG:-${VERSION}${SUFFIX}}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

bazel run //hack/release -- \
		--repo-root "$(pwd)" \
		--images \
		--images.export=true \
		--app-version="${TAG}" \
		--docker-repo="rancher"